### ISSUE TITLE
Chapter 4 Tutorial Errors

### ISSUE THREAD

**Issue by ejhgeo** [cgre-aachen/gempy#118]
Trying to work through the chapter 4 tutorial on gravity and a couple of issues have come up. 
First, in cell 4, in 'geo_data.set_formation_values', I get the following error: 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-42-f60695fdd077> in <module>()
----> 1 geo_data.set_formation_values([2.61, 2.92, 3.1, 2.91, 2.61])
      2 geo_data.formations

AttributeError: 'InputData' object has no attribute 'set_formation_values'
```
Everything else I've coded before this cell is identical to the tutorial, so I'm not sure why it is not working. I also had a similar issue with grid class in chapter 2, with the error: 'GridClass' has no attribute 'set_regular_grid'. 

Later on in chap 4, some of my output differs from the tutorial (perhaps because of not being able to run the above cell to assign the densities). In cell 28, when using the exact same lines of code as in the tutorial, I get an error: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-41-e3d477490ad8> in <module>()
      2 import theano.tensor as T
      3 geomodel = theano.OpFromGraph(interp_data_grav.interpolator.tg.input_parameters_list(),
----> 4                               [interp_data_grav.interpolator.tg.compute_forward_gravity(0)[-1]],
      5                               on_unused_input='ignore')

TypeError: compute_forward_gravity() takes 1 positional argument but 2 were given
```
When I leave the () empty instead of 0, it doesn't throw an error, but I have a problem with cell 34 and 37:

```
/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/theano/gof/fg.py in __import__(self, apply_node, check, reason)
    389                                      "for more information on this error."
    390                                      % (node.inputs.index(r), str(node)))
--> 391                         raise MissingInputError(error_msg, variable=r)
    392 
    393         for node in new_nodes:

MissingInputError: ('The following error happened while compiling the node', OpFromGraph{inline=False}(<TensorType(float64, matrix)>, <TensorType(float64, vector)>, <TensorType(float64, vector)>, <TensorType(float64, vector)>, <TensorType(float64, matrix)>, <TensorType(float64, matrix)>, List with the number of formations, Length of interfaces in every series, Number of faults, Length of foliations in every series, Grade of the universal drift, Coordinates of the grid points to interpolate, <TensorType(float64, vector)>, <TensorType(float64, scalar)>, Range, Covariance at 0, <TensorType(float64, scalar)>, <TensorType(float64, matrix)>, Nugget effect of gradients, Nugget effect of scalar, Value of the formation, Number of points per formation accumulative, Value of the formation to compute), '\n', 'Input 0 of the graph (indices start from 0), used to compute ScalarFromTensor(<TensorType(int32, scalar)>), was not provided and not given a value. Use the Theano flag exception_verbosity=\'high\', for more information on this error.\n \nBacktrace when that variable is created:\n\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2901, in run_ast_nodes\n    if self.run_code(code, result):\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File "<ipython-input-25-1ff2cea587b4>", line 4, in <module>\n    [interp_data_grav.interpolator.tg.compute_forward_gravity()[-1]],\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/gempy/theano_graph.py", line 1897, in compute_forward_gravity\n    lith_matrix, fault_matrix, pfai = self.compute_geological_model()\n  File "/anaconda3/envs/gempygrav3.5/lib/python3.5/site-packages/gempy/theano_graph.py", line 1761, in compute_geological_model\n    return_list=True\n')
```
I know it's a long post, but perhaps the errors are related? I'm trying to understand what the problem is since my script is identical to the tutorials, and I'm not entirely familiar with what all the functions and commands are doing in this section since there's less commenting. Any help is appreciated. Thanks!

**Comment by Leguark** [comment]
Oh yes, I should delete that tutorial. Gravity inversions in pymc3 is still work in progress. That part should be running around summer with much better documentation and API. If you need to do gravity inversions like what we did in Wellmann et al 2017 or the example I have in the GemPy paper. The trick is to couple tutorial 3 and tutorial 5 (the paper notebooks are doing something similar but right now I think the inversion is also broken, you could go back to the 1.0 release to make them run).

Sorry for the inconvenience, in this topic we have quite a bit prepared for publishing. Along the next year we will improve that part of the software a lot.
