### ISSUE TITLE
Typing: AttributeError: module 'gempy' has no attribute 'Solution'

### ISSUE THREAD

**Issue by pytzcarraldo** [cgre-aachen/gempy#335]
**Describe the bug**
pip-installed gempy crashes on import due to faulty typing reference in vista plotting function

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gempy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/namur/coding/gempy/gempy/__init__.py", line 10, in <module>
    import gempy.plot.plot_api as _plot
  File "/home/namur/coding/gempy/gempy/plot/plot_api.py", line 38, in <module>
    from .vista import _Vista as Vista
  File "/home/namur/coding/gempy/gempy/plot/vista.py", line 56, in <module>
    class Vista:
  File "/home/namur/coding/gempy/gempy/plot/vista.py", line 108, in Vista
    name='lith',
AttributeError: module 'gempy' has no attribute 'Solution'
```

Reported by @WestfalNamur

**Comment by pytzcarraldo** [comment]
Solved by #336
