### ISSUE TITLE
Theano datatype exception when creating model in python from ndarrays

### ISSUE THREAD

**Issue by TobiasGlaubach** [cgre-aachen/gempy#339]
**Describe the bug**
Maybe I am missing something here, but when I construct a model from numpy ndarrays and cast the data to any of the following types: `float` `float32 `or `double` the computation fails and `theano` gives an exception about datatypes involved.

**To Reproduce**
Generate some data like this:

```python
import gempy as gp
import numpy as np
import pandas as pd

s_names = 'surface_1 surface_2'.split()

v_i = np.array([[0.0, 0.0, 0.5, 'surface_2'],
       [0.0, 0.1111111111111111, 0.5074074074074074, 'surface_2'],
       [0.0, 0.2222222222222222, 0.5296296296296297, 'surface_2'],
       [0.0, 0.3333333333333333, 0.5666666666666667, 'surface_2'],
       [0.0, 0.4444444444444444, 0.6185185185185185, 'surface_2']],
      dtype=object)
df_i = pd.DataFrame(v_i, columns='X Y Z formation'.split())

v_N = np.array([[0.5925925925925927, 0.9629629629629629, 1.0580246913580247, 0.0,
        -0.749837855365093, 0.6616216370868461, 'surface_2'],
       [0.9629629629629629, 0.037037037037037035, 0.5024691358024692,
        0.0, -0.06651901052377403, 0.9977851578566089, 'surface_2'],
       [0.7407407407407406, 0.037037037037037035, 0.5024691358024692,
        0.0, -0.06651901052377403, 0.9977851578566089, 'surface_2'],
       [0.8518518518518517, 0.07407407407407407, 0.5049382716049383, 0.0,
        -0.06651901052377403, 0.9977851578566089, 'surface_2'],
       [0.5925925925925927, 0.037037037037037035, 0.5024691358024692,
        0.0, -0.06651901052377403, 0.9977851578566089, 'surface_2']],
      dtype=object)
df_N = pd.DataFrame(v_N, columns='X Y Z G_X G_Y G_Z formation'.split())

discretization = [5,20,20]

extend = [df_i['X'].min(), df_i['X'].max(),
          df_i['Y'].min(), df_i['Y'].max(),
          df_i['Z'].min(), df_i['Z'].max()]

```

then make a gempy model out of this based on the code in https://github.com/cgre-aachen/gempy/blob/master/notebooks/tutorials/ch1-Fundamentals/ch1-2_Data_Manipulation.ipynb

```python
# Load data into a gempy model
geo_model = gp.create_model('test')
gp.init_data(geo_model, extend, discretization)

faults = gp.Faults()

series = gp.Series(faults)
series.set_series_index(['Strat_Series'])

surfaces = gp.Surfaces(series)
surfaces.set_surfaces_names(s_names)
surfaces.set_basement()

surface_points = gp.SurfacePoints(surfaces)
xyz = df_i.values[:,:3].astype('float32')
formations = [str(f) for f in df_i.values[:,3]]

surface_points.set_surface_points(xyz, formations)

orientations = gp.Orientations(surfaces)
xyz = df_N.values[:,:3].astype('float32')
G_xyz = df_N.values[:,3:6].astype('float32')
formations = [str(f) for f in df_N.values[:,6]]
orientations.set_orientations(xyz, G_xyz, surface=formations)

gp.map_series_to_surfaces(geo_model, {'Strat_Series':  s_names})

```
then try to compute the model like this:

```python
interp_data = gp.set_interpolation_data(geo_model, 
                                        compile_theano=True,
                                        theano_optimizer='fast_run')
sol = gp.compute_model(geo_model)
```

Gives the following error:

```
Active grids: ['regular']
Traceback (most recent call last):

  File "C:\Users\tobia\OneDrive\Desktop\Projects\GeologicalModelling\GeoModellingJupyter\M2_GeoModelling\untitled0.py", line 69, in <module>
    gp.map_series_to_surfaces(geo_model, {'Strat_Series':  s_names})

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\gempy_api.py", line 74, in map_series_to_surfaces
    geo_model.map_series_to_surfaces(mapping_object, set_series, sort_geometric_data, remove_unused_series)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\model.py", line 496, in map_series_to_surfaces
    self.update_from_series()

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\model.py", line 817, in update_from_series
    self.interpolator.set_theano_shared_structure(reset_ctrl=True)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\interpolator.py", line 599, in set_theano_shared_structure
    self.set_theano_shared_relations()

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\interpolator.py", line 688, in set_theano_shared_relations
    self.set_theano_shared_fault_relation()

  File "C:\Users\tobia\Anaconda3\lib\site-packages\gempy\core\interpolator.py", line 655, in set_theano_shared_fault_relation
    self.theano_graph.fault_relation.set_value(self.faults.faults_relations_df.values)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\theano\compile\sharedvalue.py", line 148, in set_value
    self.container.value = copy.deepcopy(new_value)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\theano\gof\link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)

  File "C:\Users\tobia\Anaconda3\lib\site-packages\theano\tensor\type.py", line 140, in filter
    raise TypeError(err_msg)

TypeError: ('TensorType(int32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([], shape=(0, 0), dtype=float64)"', 'Container name "fault relation matrix"')
```

Is it my error, or is there a bug in the code.
...

**Expected behavior**
Should have compiled and calculated the model. I had no problems, when importing the data from CSV.

**Desktop (please complete the following information):**
  * OS: Windows10
  * Anaconda: `Version 2020.02 Build py37_0`
  * `gempy==2.0.1`
  * `Theano==1.0.4`

**Comment by TobiasGlaubach** [comment]
Not casting the data at all before using it fails as well.

**Comment by TobiasGlaubach** [comment]
update, even when I generate some dummy data like this: 

```
v_i = np.random.randn(5, 3)
s_i = ['surface_2', 'surface_2', 'surface_2', 'surface_1', 'surface_1']
df_i = pd.DataFrame(v_i, columns='X Y Z'.split())

v_N = np.random.randn(5, 6)
s_N = ['surface_2', 'surface_2', 'surface_2', 'surface_1', 'surface_1']
df_N = pd.DataFrame(v_N, columns='X Y Z G_X G_Y G_Z'.split())
```

the error arises, did I miss an installation step for `theano`?

**Comment by Leguark** [comment]
Oh I see, when you create a Model object by gp.create_model, it automatically instantiates all the data objects you need, you can find them in geo_model.surfaces, or geo_model.surface_points and so on. Always that you use methods of the class Model you guarantee that all the data objects get updated.

What you are doing up there is creating a Model class with all its composited data objects and then create new objects (which are not linked to model) and fill the data but I guess that if you do print(geo_model.surface_points) (which is the object use for interpolation), it is empty

**Comment by TobiasGlaubach** [comment]
oh I see. Well I could have seen this before, thanks for clearing this up, and sorry for the issue!
