### ISSUE TITLE
pyvista currently in optional dependencies, but needed during gempy import

### ISSUE THREAD

**Issue by florian-wagner** [cgre-aachen/gempy#343]
Dear all,

looking forward to a GemPy introduction by @elimh today, so I just did a `pip install gempy` followed by `python -c "import gempy"` and get the following: 

``` python
~/miniconda/envs/gempy/lib/python3.8/site-packages/gempy/plot/vista.py in <module>
     34 import numpy as np
     35 import pandas as pn
---> 36 import pyvista as pv
     37 from pyvista.plotting.theme import parse_color
     38 

ModuleNotFoundError: No module named 'pyvista'
```

Either the import should be optional or `pyvista` should be moved from `optional-requirements.txt` to `requirements.txt`. 

Best wishes and stay healthy
Florian

**Comment by TobiasGlaubach** [comment]
Also when I install pyvista via pip on Anaconda 3 with python 3.7 on Win10 it fails to load the following dependency:

```python
Traceback (most recent call last):
  File "C:\Users\tobia\Anaconda3\lib\site-packages\vtk\vtkCommonKit.py", line 5, in <module>
    from .vtkCommonKitPython import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tobia/OneDrive/Desktop/Projects/GeologicalModelling/git_libraries/gempy/test/test_core/test_integration.py", line 1, in <module>
    import gempy as gp
  File "C:\Users\tobia\OneDrive\Desktop\Projects\GeologicalModelling\git_libraries\gempy\gempy\__init__.py", line 17, in <module>
    import gempy.plot.plot_api as _plot
  File "C:\Users\tobia\OneDrive\Desktop\Projects\GeologicalModelling\git_libraries\gempy\gempy\plot\plot_api.py", line 38, in <module>
    from .vista import _Vista as Vista
  File "C:\Users\tobia\OneDrive\Desktop\Projects\GeologicalModelling\git_libraries\gempy\gempy\plot\vista.py", line 36, in <module>
    import pyvista as pv
  File "C:\Users\tobia\Anaconda3\lib\site-packages\pyvista\__init__.py", line 5, in <module>
    from pyvista.plotting import *
  File "C:\Users\tobia\Anaconda3\lib\site-packages\pyvista\plotting\__init__.py", line 5, in <module>
    from .export_vtkjs import export_plotter_vtkjs, get_vtkjs_url
  File "C:\Users\tobia\Anaconda3\lib\site-packages\pyvista\plotting\export_vtkjs.py", line 55, in <module>
    import vtk
  File "C:\Users\tobia\Anaconda3\lib\site-packages\vtk\__init__.py", line 7, in <module>
    from .vtkCommonKit import *
  File "C:\Users\tobia\Anaconda3\lib\site-packages\vtk\vtkCommonKit.py", line 9, in <module>
    from vtkCommonKitPython import *
ModuleNotFoundError: No module named 'vtkCommonKitPython'

Process finished with exit code 1
```

**Comment by Leguark** [comment]
thank you @florian-wagner I added the change to the release branch 6ef3bd5
 , in the next pip hotfix it will go live! Thank you for the feedback

@TobiasGlaubach that seems a dependency hell of windows. I highly recommend to create a conda enviroment in windows. Since they place most of the dependencies in the same folder, usually there is less troubles with the system paths

**Comment by florian-wagner** [comment]
Thank you @Leguark ! Now gempy is again as easy to install as pygimli :laughing:
