### ISSUE TITLE
Bug in example breaks gh-pages deployment

### ISSUE THREAD

**Issue by alexanderzimmerman** [cgre-aachen/gempy#477]
**Describe the bug**
From https://travis-ci.org/github/cgre-aachen/gempy/jobs/699232587

```
Unexpected failing examples:
/home/travis/build/cgre-aachen/gempy/examples/integrations/gempy_discretize_emg3d.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/tenv/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 159, in call_memory
    return 0., func()
  File "/home/travis/miniconda/envs/tenv/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 466, in __call__
    exec(self.code, self.fake_main.__dict__)
  File "/home/travis/build/cgre-aachen/gempy/examples/integrations/gempy_discretize_emg3d.py", line 219, in <module>
    clim=[1e-13, 1e-8], pcolorOpts={'cmap': 'viridis', 'norm': LogNorm()})
  File "/home/travis/miniconda/envs/tenv/lib/python3.7/site-packages/discretize/View.py", line 832, in plot_3d_slicer
    clim, xlim, ylim, zlim, aspect, grid, pcolor_opts
  File "/home/travis/miniconda/envs/tenv/lib/python3.7/site-packages/discretize/View.py", line 1421, in __init__
    self.v = mesh.r(v.reshape((mesh.nC, -1), order='F'), 'CC', 'CC', 'M')
ValueError: cannot reshape array of size 245440 into shape (237568,newaxis)
```

**To Reproduce**
I don't know how this didn't appear in other recent PR's, given that I have seen no changes to master since recent successful PR's. So I think this might be difficult to reproduce. Anyway it can probably be done by checking out master and running the example.

**Comment by alexanderzimmerman** [comment]
I get the same error when running the example locally:

```
Traceback (most recent call last):
  File "examples\integrations/gempy_discretize_emg3d.py", line 219, in <module>
    clim=[1e-13, 1e-8], pcolorOpts={'cmap': 'viridis', 'norm': LogNorm()})
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\site-packages\discretize\View.py", line 832, in plot_3d_slicer
    clim, xlim, ylim, zlim, aspect, grid, pcolor_opts
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\site-packages\discretize\View.py", line 1421, in __init__
    self.v = mesh.r(v.reshape((mesh.nC, -1), order='F'), 'CC', 'CC', 'M')
ValueError: cannot reshape array of size 245440 into shape (237568,newaxis)
```

**Comment by alexanderzimmerman** [comment]
It looks like it might be a bug in the `discretize` module from conda-forge. 

```
Traceback (most recent call last):
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\pdb.py", line 1568, in _runscript
    self.run(statement)
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\users\zimme\desktop\run-gempy-examples\examples\integrations\gempy_discretize_emg3d.py", line 5, in <module>
    """
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\site-packages\discretize\View.py", line 832, in plot_3d_slicer
    clim, xlim, ylim, zlim, aspect, grid, pcolor_opts
  File "C:\Users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\site-packages\discretize\View.py", line 1421, in __init__
    self.v = mesh.r(v.reshape((mesh.nC, -1), order='F'), 'CC', 'CC', 'M')
ValueError: cannot reshape array of size 245440 into shape (237568,newaxis)
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\users\zimme\anaconda3\envs\gempy-master-2020-07-01\lib\site-packages\discretize\view.py(1421)__init__()
-> self.v = mesh.r(v.reshape((mesh.nC, -1), order='F'), 'CC', 'CC', 'M')
```

I'll try using the previous version, before their update nine days ago: https://anaconda.org/conda-forge/discretize/files

**Comment by alexanderzimmerman** [comment]
Alright I don't know about the emg3d result; but going back to discretize==0.4.13 fixes the current issue.
