### ISSUE TITLE
Import error etc.

### ISSUE THREAD

**Issue by caasox** [cgre-aachen/gempy#623]
After playing around and reinstalling a thousand times I run into the same error message everytime when I try to run the get_started.py from the tutorial section:

`No module named 'osgeo'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Active grids: ['regular']
Setting kriging parameters to their default values.
Compiling theano function...

You can find the C code in this temporary file: C:\Users\Schimpf\AppData\Local\Temp\theano_compilation_error_jagvlj3b
Traceback (most recent call last):
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan_perform_ext.py", line 48, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan_perform_ext.py", line 63, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_started.py", line 46, in <module>
    gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\gempy\api_modules\setters.py", line 108, in set_interpolator
    geo_model._interpolator.compile_th_fn_geo(inplace=True, grid=grid)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\gempy\core\interpolator.py", line 1124, in compile_th_fn_geo
    self.theano_graph.theano_output(),
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 631, in theano_output
    solutions[:9] = self.compute_series()
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 496, in compute_series
    profile=False
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan.py", line 849, in scan
    profile=False)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\gof\link.py", line 830, in make_all
    'py')]
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan_op.py", line 866, in make_thunk
    on_unused_input='ignore')
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan_op.py", line 925, in make_thunk
    from . import scan_perform_ext
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\scan_module\scan_perform_ext.py", line 122, in <module>
    hide_symbols=False)
  File "C:\Users\Schimpf\Anaconda3\envs\gempy\lib\site-packages\theano\gof\cmodule.py", line 2411, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', for{cpu,scan_fn}(Elemwise{minimum,no_inplace}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, Subtensor{:int64:}.0, IncSubtensor{Set;:int64:}.0), '\n', 'Compilation failed (return status=1): In file included from C:\\Users\\Schimpf\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_79_Stepping_1_GenuineIntel-3.7.10-64\\scan_perform\\mod.cpp:782:0:\r. C:/Users/Schimpf/Anaconda3/envs/gempy/Library/mingw-w64/include/c++/5.3.0/complex:795:5: internal compiler error: Segmentation fault\r.      { return std::log(__z) / log(_Tp(10.0)); }\r.      ^\r. libbacktrace could not find executable to open\r. Please submit a full bug report,\r. with preprocessed source if appropriate.\r. See <https://sourceforge.net/projects/msys2> for instructions.\r. ')`

I'm a little lost now, so please help me.

Best regards,

caasox

**Comment by caasox** [comment]
Nobody an answer?

**Comment by flohorovicic** [comment]
I can personally not really help with installation errors on Windows (they are often related to conflicting installations of other Python packages/ software on the system, as far as I know), but to move forward:

- Can you tell us a bit about your system, Python/ Anaconda versions, etc.?
- Did you install in a fresh anaconda environment (looks like it above, just to be sure)?
- One thing to try: Alex has a really good installation instruction for gemgis, including the gempy installation - maybe some good pointers in there: https://gemgis.readthedocs.io/en/stable/getting_started/installation.html

Sorry if I can't give a better answer, as I am not as deep in the theano part, where this error seems to originate from... someone else would have to answer on that part.

**Comment by hadismasihi** [comment]
Hi, I'm not very good at installing libraries, but I had a problem installing gdal and always had the error like 'No module named' osgeo '.
I entered this code to install this library with Anacanda and Python 3.8:
conda install -c conda-forge / label / cf202003 gdal
Because it installed an older and more appropriate version and the problem was easily solved and then "pip install gempy"

**Comment by hadismasihi** [comment]
Hi, I'm not very good at installing libraries, but I had a problem installing gdal and always had the error like 'No module named' osgeo '.
I entered this code to install this library with Anacanda and Python 3.8:
conda install -c conda-forge / label / cf202003 gdal
Because it installed an older and more appropriate version and the problem was easily solved and then "pip install gempy"

**Comment by AlexanderJuestel** [comment]
Hello @hadismasihi, 

we can only recommend to install gdal not as a standalone package. What you could try is to install the geopandas package. They should have resolved all the issues that may arise with the gdal installation. Once that worked, you could try installing GemPy again

**Comment by hadismasihi** [comment]
Yes, thank you for your attention

**Comment by AlexanderJuestel** [comment]
Has there been new developments here?

**Comment by Espressorite** [comment]
Hi,

I created a new environment in anconda and re downloaded my packages which has worked! No longer getting the error.

I will monitor it for a few days and let you know if it reoccurs again.

Thank for your help,

Joe

**Comment by AlexanderJuestel** [comment]
Closing as the problem seems to be solved for now. Feel free to reopen if you have any questions or concerns.
