### ISSUE TITLE
error when running python scripts

### ISSUE THREAD

**Issue by yangfanswjtu** [cgre-aachen/gempy#632]
hello,
There was an error when I ran the python example script "ch1_1_basics.py", see the following:

(base) D:\>python basics.py
No module named 'osgeo'
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configparser.py", line 168, in fetch_val_for_key
    return theano_cfg.get(section, option)
  File "D:\ProgramData\Anaconda3\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "D:\ProgramData\Anaconda3\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configparser.py", line 328, in __get__
    delete_key=delete_key)
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configparser.py", line 172, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas.ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "basics.py", line 8, in <module>
    import gempy as gp
  File "D:\ProgramData\Anaconda3\lib\site-packages\gempy\__init__.py", line 24, in <module>
    from gempy.gempy_api import *
  File "D:\ProgramData\Anaconda3\lib\site-packages\gempy\gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "D:\ProgramData\Anaconda3\lib\site-packages\gempy\core\model.py", line 17, in <module>
    from gempy.core.interpolator import InterpolatorModel, InterpolatorGravity
  File "D:\ProgramData\Anaconda3\lib\site-packages\gempy\core\interpolator.py", line 10, in <module>
    import theano
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\__init__.py", line 124, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\scan_module\__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\scan_module\scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\tensor\__init__.py", line 17, in <module>
    from theano.tensor import blas
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\tensor\blas.py", line 155, in <module>
    from theano.tensor.blas_headers import blas_header_text
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\tensor\blas_headers.py", line 987, in <module>
    if not config.blas.ldflags:
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configparser.py", line 332, in __get__
    val_str = self.default()
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configdefaults.py", line 1422, in default_blas_ldflags
    check_mkl_openmp()
  File "D:\ProgramData\Anaconda3\lib\site-packages\theano\configdefaults.py", line 1262, in check_mkl_openmp
    """)
RuntimeError:
To use MKL 2018 with Theano either update the numpy conda packages to
their latest build or set "MKL_THREADING_LAYER=GNU" in your
environment.

so , How should I handle it? Thanks for your time.

**Comment by AlexanderJuestel** [comment]
Hello,

Could you maybe try to install pyqt5?
This may solve your installation issues

**Comment by AlexanderJuestel** [comment]
Any luck with the suggested solution so far?

**Comment by yangfanswjtu** [comment]
hi Alexander ,
Thanks for your suggestion, Gempy is ready to work normally within docker. However, there is another problem, that is, the plot_3d method cannot be run, and once it has been run, it will prompt the kernel to crash, but the plot_2d method can be called normally. @AlexanderJuestel

**Comment by Japhiolite** [comment]
Hi @yangfanswjtu 

does that problem with the 3d plot still occur? What's the status on this issue?

Cheers
Jan

**Comment by Japhiolite** [comment]
Hi @yangfanswjtu 

I'm closing this issue, as there was now answer. If you still have the problem, feel free to re-open the issue.

Cheers
Jan
