### ISSUE TITLE
[DEP] Not possible to import gempy

### ISSUE THREAD

**Issue by car-rivera** [cgre-aachen/gempy#750]
**Describe the bug**
After installing gemgis and gempy via PyPI, I am not able to import gempy either from PyCharm or from batch console. You can read below my python version and all the python packages installed locally so far.

**To Reproduce**
I am just doing a simple import.

C:\CVI\13_Scripts\scripts>python test_gempy.py
**_Script:_**
import sys
print('Python version: ', sys.version)
print('Version info: ', sys.version_info)
import rasterio
import geopandas as gpd
import gempy as gp
import gemgis as gg

**_Output_**
**Python version:  3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]**
**Version info:  sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)**
C:\Python3.10\lib\site-packages\geopandas\_compat.py:123: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
Traceback (most recent call last):
  File "C:\CVI\13_Scripts\scripts\test_gempy.py", line 7, in <module>
    import gempy as gp
  File "C:\Python3.10\lib\site-packages\gempy\__init__.py", line 25, in <module>
    from gempy.gempy_api import *
  File "C:\Python3.10\lib\site-packages\gempy\gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "C:\Python3.10\lib\site-packages\gempy\core\model.py", line 11, in <module>
    from gempy.core.data_modules.geometric_data import Orientations, SurfacePoints, \
  File "C:\Python3.10\lib\site-packages\gempy\core\data_modules\geometric_data.py", line 10, in <module>
    from gempy.core.data import Surfaces, Grid
  File "C:\Python3.10\lib\site-packages\gempy\core\data.py", line 8, in <module>
    import seaborn as sns
  File "C:\Python3.10\lib\site-packages\seaborn\__init__.py", line 5, in <module>
    from .relational import *  # noqa: F401,F403
  File "C:\Python3.10\lib\site-packages\seaborn\relational.py", line 17, in <module>
    from ._statistics import EstimateAggregator
  File "C:\Python3.10\lib\site-packages\seaborn\_statistics.py", line 31, in <module>
    from scipy.stats import gaussian_kde
  File "C:\Python3.10\lib\site-packages\scipy\stats\__init__.py", line 485, in <module>
    from ._stats_py import *
  File "C:\Python3.10\lib\site-packages\scipy\stats\_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "C:\Python3.10\lib\site-packages\scipy\spatial\__init__.py", line 105, in <module>
    from ._kdtree import *
  File "C:\Python3.10\lib\site-packages\scipy\spatial\_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
  File "_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**_Below you can read all the list of packages installed in my laptop:_**

C:\Python3.10\Scripts>pip freeze
aenum==3.1.11
affine==2.3.1
aiohttp==3.8.3
aiosignal==1.2.0
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.1.0
Babel==2.11.0
backcall==0.2.0
beartype==0.11.0
beautifulsoup4==4.11.1
bleach==5.0.1
bqplot==0.12.36
branca==0.6.0
certifi==2022.9.24
cffi==1.15.1
cftime==1.6.2
charset-normalizer==2.1.1
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
colour==0.1.5
comm==0.1.2
contourpy==1.0.5
cycler==0.11.0
Cython==0.29.33
dash==2.7.1
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
debugpy==1.6.5
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
exceptiongroup==1.0.4
executing==1.2.0
fastjsonschema==2.16.2
filelock==3.9.0
Fiona==1.8.22
Flask==2.2.2
folium==0.14.0
fonttools==4.37.3
fqdn==1.5.1
frozenlist==1.3.1
gdown==4.6.0
gemgis==1.0.5
gempy==2.2.12
geojson==2.5.0
geopandas==0.12.2
geostatspy==0.0.26
hjson==3.1.0
homematicip==1.0.13
idna==3.4
imageio==2.22.4
iniconfig==1.1.1
ipyevents==2.0.1
ipyfilechooser==0.6.0
ipykernel==6.19.4
ipyleaflet==0.17.2
ipython==8.7.0
ipython-genutils==0.2.0
ipytree==0.2.2
ipywidgets==8.0.4
isoduration==20.11.0
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter-events==0.5.0
jupyter_client==7.4.8
jupyter_core==5.1.2
jupyter_server==2.0.6
jupyter_server_terminals==0.4.3
jupyterlab==3.5.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.18.0
kiwisolver==1.4.4
leafmap==0.15.0
llvmlite==0.39.1
LoopProjectFile==0.0.22
lxml==4.9.2
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
mplstereonet==0.6.2
multidict==6.0.2
munch==2.5.0
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.1
nest-asyncio==1.5.6
netCDF4==1.6.2
networkx==2.8.8
notebook==6.5.2
notebook_shim==0.2.2
numba==0.56.4
numpy==1.21.6
OpenGeode-core==12.5.12
OpenGeode-Geosciences==5.7.8
OpenGeode-GeosciencesIO==3.12.3
OpenGeode-IO==5.23.3
OWSLib==0.27.2
packaging==21.3
pandas==1.3.4
pandocfilters==1.5.0
parso==0.8.3
patsy==0.5.3
pickleshare==0.7.5
Pillow==9.2.0
platformdirs==2.6.2
plotly==5.11.0
pluggy==1.0.0
pooch==1.6.0
prometheus-client==0.15.0
prompt-toolkit==3.0.33
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
pygeos==0.14
Pygments==2.13.0
pyparsing==3.0.9
pyproj==3.4.0
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyrsistent==0.19.3
pyshp==2.3.1
PySocks==1.7.1
pystac==1.6.1
pystac-client==0.5.1
pytest==7.2.0
python-box==6.1.0
python-dateutil==2.8.2
python-json-logger==2.0.4
python-pptx==0.6.21
pytz==2022.6
pyvista==0.37.0
pyvistaqt==0.9.0
PyWavelets==1.4.1
pywin32==305
pywinpty==2.0.10
PyYAML==6.0
pyzmq==24.0.1
QtPy==2.3.0
rasterio==1.3.4
requests==2.28.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
scikit-fmm==2022.8.15
scikit-image==0.19.3
scikit-learn==1.2.0
scipy==1.10.0
scooby==0.7.0
seaborn==0.12.1
Send2Trash==1.8.0
Shapely==1.8.5.post1
six==1.16.0
sniffio==1.3.0
snuggs==1.4.7
soupsieve==2.3.2.post1
stack-data==0.6.2
statsmodels==0.13.5
tenacity==8.1.0
terminado==0.17.1
Theano==1.0.5
threadpoolctl==3.1.0
tifffile==2022.10.10
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
tqdm==4.64.1
traitlets==5.6.0
traittypes==0.2.1
uri-template==1.2.0
urllib3==1.26.13
vtk==9.2.0rc2
wcwidth==0.2.5
webcolors==1.12
webencodings==0.5.1
websocket-client==1.4.2
websockets==10.4
Werkzeug==2.2.2
whitebox==2.2.0
whiteboxgui==2.2.0
widgetsnbextension==4.0.5
wslink==1.8.2
xarray==2022.3.0
XlsxWriter==3.0.7
xyzservices==2022.9.0
yarl==1.8.1

**Comment by AlexanderJuestel** [comment]
Hello @car-rivera, 

try testing this approach here. It always helped me to install Geopandas and rasterio first to make sure that GDAL is installed properly: https://gemgis.readthedocs.io/en/latest/getting_started/installation.html

**Comment by car-rivera** [comment]
@AlexanderJuestel, thanks for the reply. But as you can see in my results from "pip freeze" above,  I do have installed rasterio and geopandas. Any other hint?
Of course, I read the documentation page you sent me. ;-).

**Comment by Japhiolite** [comment]
@car-rivera can you have a look if the problem persists with Python 3.9?

**Comment by car-rivera** [comment]
@Japhiolite, so is GemPy not supported in the latest Python version? What is the official python version supported?
Most of my stuff is with Python 3.10, preferable I would like to stick to that version.

**Comment by Michael-P-Crisp** [comment]
I was also unable to import it using Python 3.10 when using pip, although it does work with Python 3.10 with conda.
It imports for me using Python 3.9 with pip.

Although when compiling my model using 

`gp.set_interpolator(geo_model,
                    compile_theano=True,
                    theano_optimizer='fast_compile',
                    )`

I get this import error, which I'm guessing is for a custom module created by GemPy/Theano specifically for this geo model.
```
INFO (theano.gof.compilelock): Refreshing lock C:\Users\CRI92972\AppData\Local\Theano\compiledir_Windows-10-10.0.19044-SP0-Intel64_Family_6_Model_158_Stepping_13_GenuineIntel-3.9.13-64\lock_dir\lock
Traceback (most recent call last):
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-59-92fb73273a59>", line 1, in <module>
    gp.set_interpolator(geo_model,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\api_modules\setters.py", line 108, in set_interpolator
    geo_model._interpolator.compile_th_fn_geo(inplace=True, grid=grid)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\interpolator.py", line 1123, in compile_th_fn_geo
    self.theano_graph.theano_output(),
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 631, in theano_output
    solutions[:9] = self.compute_series()
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 465, in compute_series
    series, self.updates1 = theano.scan(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\scan_module\scan.py", line 774, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 2141, in compute_a_series
    self.compute_scalar_field(weights, grid,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 434, in compute_scalar_field
    return self.scalar_field_at_all(weights, grid_val, fault_matrix)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\gempy\core\theano_modules\theano_graph_pro.py", line 1725, in scalar_field_at_all
    Z_x_loop, updates3 = theano.scan(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\scan_module\scan.py", line 843, in scan
    dummy_f = function(dummy_args,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\link.py", line 826, in make_all
    thunks += [node.op.make_thunk(node,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\scan_module\scan_op.py", line 861, in make_thunk
    self.fn = function(wrapped_inputs,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\vm.py", line 1087, in make_all
    thunks.append(node.op.make_thunk(node,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cmodule.py", line 2420, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\CRI92972\Documents\gempy\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed while importing m7b9aaee4c7e7a84c9349e61bca7c6a325d685aa6ac844a5dba2a836e7ea148e3: The specified module could not be found.
```

**Comment by car-rivera** [comment]
I've tried now with Python 3.9.13. If I simply do "**_import gempy as gp_**", then the following error is given.
I am concluding that it is not possible to install gempy with pip. Unfortunately, Anaconda is not an option for me, since this is only free for academic purposes. I think it is a very limiting factor in case you would like to promote the use of Gempy in the industry. Thanks anyway for your help!

C:\Python3.9\python.exe C:\CVI\13_Scripts\gempy\test_gempy.py 
No module named 'osgeo'
Not subsurface compatibility available
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "C:\CVI\13_Scripts\gempy\test_gempy.py", line 2, in <module>
    import gempy as gp
  File "C:\Python3.9\lib\site-packages\gempy\__init__.py", line 25, in <module>
    from gempy.gempy_api import *
  File "C:\Python3.9\lib\site-packages\gempy\gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "C:\Python3.9\lib\site-packages\gempy\core\model.py", line 20, in <module>
    from gempy.plot.decorators import *
  File "C:\Python3.9\lib\site-packages\gempy\plot\decorators.py", line 2, in <module>
    from gempy.plot.vista import GemPyToVista
  File "C:\Python3.9\lib\site-packages\gempy\plot\vista.py", line 36, in <module>
    from pyvista.plotting import parse_color
ImportError: cannot import name 'parse_color' from 'pyvista.plotting' (C:\Python3.9\lib\site-packages\pyvista\plotting\__init__.py)

Process finished with exit code 1

**Comment by AlexanderJuestel** [comment]
Dear Carlos,

The last error that appears (parse color) has already been fixed on the main branch and @Japhiolite is working on a release within the next few weeks. A temporary solution would be to downgrade pyvista to like version 0.3x were parse color is still available. Than this error should be gone.

**Comment by car-rivera** [comment]
Dear @AlexanderJuestel 
Can you be more precise in the exact pyvista version? See below.

ERROR: Could not find a version that satisfies the requirement pyvista==0.3 (from versions: 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.22.0, 0.22.1, 0.22.2, 0.22.4, 0.23.0, 0.23.1, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.25.1, 0.25.2, 0.25.3, 0.26.0, 0.26.1, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.28.0rc1, 0.28.0rc2, 0.28.0rc3, 0.28.0, 0.28.1, 0.29.0rc1, 0.29.0, 0.29.1, 0.30.0rc1, 0.30.0, 0.30.1, 0.31.0, 0.31.1, 0.31.2, 0.31.3, 0.32.dev0, 0.32.0, 0.32.1, 0.33.dev0, 0.33.0, 0.33.1, 0.33.2, 0.33.3, 0.34.0, 0.34.1, 0.34.2, 0.35.1, 0.35.2, 0.36.0, 0.36.1, 0.37.0, 0.38.0, 0.38.1)
ERROR: No matching distribution found for pyvista==0.3

For example, if I downgrade to pyvista-0.30.0, then I start getting other issues, e.g. the vtk from pyvista does not work.

Would you mind to write the exact package version of **_each of the lines below_**. According to GemPy documentation, these below are needed. Thanks!

**Dependencies**
GemPy requires Python 3.x and makes use of numerous open-source libraries:

- pandas
- Theano>=1.0.4
- matplotlib
- numpy
- pytest
- seaborn>=0.9
- networkx
- scikit-image>=0.17
- pyvista

**Optional requirements:**

- gdal
- qgrid==1.3.0
- pymc3
- pyevtk
- pyqrcode
- mplstereonet

**Comment by AlexanderJuestel** [comment]
Hello, 

these are the versions that I have in a working GemPy environment. However, certain packages are installed via conda. It has been a long time that I tried installing gempy on its own. The way that has worked the best for me the last couple of months was to follow the gemgis installation instructions where it is recommended to install geopandas, rasterio and pyvista via conda-forge. Then, gempy and gemgis can easily installed via pip. 

**Dependencies**
GemPy requires Python 3.x and makes use of numerous open-source libraries:

- pandas==1.3.4
- Theano>=1.0.4
- matplotlib==3.6.3
- numpy==1.21.0
- pytest==7.2.1
- seaborn>=0.9
- networkx==3.0
- scikit-image>=0.17
- pyvista==0.24.3

**Optional requirements:**

- gdal=3.6.2
- qgrid==1.3.0
- pymc3
- pyevtk
- pyqrcode
- mplstereonet

**Comment by AlexanderJuestel** [comment]
@car-rivera did you manage to install gempy? 

I will add your issue to our GemPy 2.3 Milestone. We hope to fix many of the dependency issues in GemPy 2.3 which should be available in the next coming weeks!

**Comment by Michael-P-Crisp** [comment]
No I've given up and am waiting for the next version.

**Comment by AlexanderJuestel** [comment]
GemPy 2.3 has been released and the issue should have been solved now! Please reopen if you still have issues with the installation. 

See https://github.com/cgre-aachen/gempy/releases/tag/v2.3.0 for more information
