### ISSUE TITLE
Installation succeeded but `import gempy` failed

### ISSUE THREAD

**Issue by kerim371** [cgre-aachen/gempy#775]
**Describe the bug**
I'm getting started with `gempy`.
I created venv and successfully installed gempy using `python -m pip install gempy`.
The command `import gempy` produces the following error:
```
/home/kerim/python/3.9.1/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
No module named 'osgeo'
Not subsurface compatibility available

You can find the C code in this temporary file: /tmp/theano_compilation_error_vsrpia9n
Traceback (most recent call last):
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/gof/lazylinker_c.py", line 76, in <module>
    raise ImportError(
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/gof/lazylinker_c.py", line 99, in <module>
    raise ImportError(
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/gempy/__init__.py", line 25, in <module>
    from gempy.gempy_api import *
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/gempy/gempy_api.py", line 17, in <module>
    from gempy.core.model import Project
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/gempy/core/model.py", line 17, in <module>
    from gempy.core.interpolator import InterpolatorModel, InterpolatorGravity
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/gempy/core/interpolator.py", line 9, in <module>
    import theano
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/__init__.py", line 110, in <module>
    from theano.compile import (
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/compile/__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/gof/vm.py", line 674, in <module>
    from . import lazylinker_c
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/gof/lazylinker_c.py", line 139, in <module>
    cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
  File "/home/kerim/python/3.9.1/lib/python3.9/site-packages/theano/gof/cmodule.py", line 2410, in compile_str
    raise Exception('Compilation failed (return status=%s): %s' %
Exception: Compilation failed (return status=1): /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(abstract.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(boolobject.o): relocation R_X86_64_32S against symbol `_Py_FalseStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bytearrayobject.o): relocation R_X86_64_32S against symbol `PyByteArray_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bytesobject.o): relocation R_X86_64_32 against symbol `PyBytesIter_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(call.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(capsule.o): relocation R_X86_64_32 against symbol `PyCapsule_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(exceptions.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(genericaliasobject.o): relocation R_X86_64_32 against symbol `Py_GenericAliasType' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(floatobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(frameobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(iterobject.o): relocation R_X86_64_32 against symbol `PySeqIter_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(listobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(longobject.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(dictobject.o): relocation R_X86_64_32S against `.text.hot' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(memoryobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(methodobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(moduleobject.o): relocation R_X86_64_32 against symbol `PyModuleDef_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(object.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(obmalloc.o): relocation R_X86_64_32 against `.text.hot' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(picklebufobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(rangeobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(setobject.o): relocation R_X86_64_32 against symbol `PyFrozenSet_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(sliceobject.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(structseq.o): relocation R_X86_64_32S against `.text.hot' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(tupleobject.o): relocation R_X86_64_32S against symbol `PyTuple_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(typeobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(unicodeobject.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(unicodectype.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(weakrefobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_warnings.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(ceval.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(codecs.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(compile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(errors.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(future.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getargs.o): relocation R_X86_64_32S against symbol `PyDict_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(import.o): relocation R_X86_64_32S against symbol `PyModule_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(importdl.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(initconfig.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(marshal.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(modsupport.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pathconfig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(peephole.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(preconfig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pyhash.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pylifecycle.o): relocation R_X86_64_32 against symbol `_PyRuntime' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pymath.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pystate.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pythonrun.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pytime.o): relocation R_X86_64_32S against symbol `PyFloat_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bootstrap_hash.o): relocation R_X86_64_32 against symbol `_Py_HashSecret' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(symtable.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(sysmodule.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(thread.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(traceback.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getopt.o): relocation R_X86_64_32S against `.rodata.str4.4' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pystrtod.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pystrhex.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(dtoa.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(formatter_unicode.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(fileutils.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(dynload_shlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getpath.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(gcmodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(posixmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(errnomodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pwdmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_sre.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_codecsmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_weakref.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_functoolsmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_operator.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_collectionsmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_abc.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(itertoolsmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(atexitmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(signalmodule.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_stat.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(timemodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_threadmodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_localemodule.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_iomodule.o): relocation R_X86_64_32 against hidden symbol `_PyIO_Module' can not be used when making a shared object. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(iobase.o): relocation R_X86_64_32S against symbol `_Py_TrueStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(fileio.o): relocation R_X86_64_32S against symbol `PyFloat_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bytesio.o): relocation R_X86_64_32 against symbol `_Py_FalseStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bufferedio.o): relocation R_X86_64_32S against symbol `PyFloat_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(textio.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(stringio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(faulthandler.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_tracemalloc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(_peg_parser.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(symtablemodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(xxsubtype.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getbuildinfo.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(acceler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(grammar1.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(token.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(peg_api.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(parsetok.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(tokenizer.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(accu.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bytes_methods.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(cellobject.o): relocation R_X86_64_32S against symbol `PyCell_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(classobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(codeobject.o): relocation R_X86_64_32S against symbol `PyCode_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(complexobject.o): relocation R_X86_64_32S against symbol `PyComplex_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(descrobject.o): relocation R_X86_64_32 against symbol `PyClassMethodDescr_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(enumobject.o): relocation R_X86_64_32S against symbol `PyReversed_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(genobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(fileobject.o): relocation R_X86_64_32 against symbol `PyStdPrinter_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(funcobject.o): relocation R_X86_64_32 against symbol `PyStaticMethod_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(interpreteridobject.o): relocation R_X86_64_32S against symbol `_PyInterpreterID_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(odictobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(namespaceobject.o): relocation R_X86_64_32 against symbol `_PyNamespace_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(Python-ast.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(ast.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(ast_opt.o): relocation R_X86_64_32S against symbol `PyFrozenSet_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(ast_unparse.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(bltinmodule.o): relocation R_X86_64_32 against symbol `PyFilter_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(context.o): relocation R_X86_64_32 against symbol `PyContext_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getcopyright.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getplatform.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getversion.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(hamt.o): relocation R_X86_64_32 against symbol `_PyHamt_Type' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(hashtable.o): relocation R_X86_64_32 against symbol `PyMem_Free' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(mystrtoul.o): relocation R_X86_64_32S against symbol `_PyLong_DigitValue' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(structmember.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(parser.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(pegen.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(parse.o): relocation R_X86_64_32 against hidden symbol `_PyPegen_expect_token' can not be used when making a shared object. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(parse_string.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(myreadline.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. /usr/bin/ld: /home/kerim/python/3.9.1/lib/libpython3.9.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC. collect2: error: ld returned 1 exit status.
```

**Desktop (please complete the following information):**
  * OS: Ubuntu 20.04
  * GemPy Version 2.2.12 (installed with `pip`)

**Comment by AlexanderJuestel** [comment]
Dear @kerim371, 

that is an error I have not seen before. We will have to check that out!

Thanks for reporting

**Comment by Japhiolite** [comment]
Likely obsolete with the transition to aesara. It's indeed a more exotic theano error to my knowledge and may be connected to your custom build.

**Comment by AlexanderJuestel** [comment]
GemPy 2.3 has been released and the issue should have been solved now! Please reopen if you still have issues with the installation.

See https://github.com/cgre-aachen/gempy/releases/tag/v2.3.0 for more information
