### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by ounie-os** [cgre-aachen/gempy#786]
```
Compiling theano function...
Traceback (most recent call last):
  File "D:\python\gempy-main\examples\tutorials\ch1_fundamentals\ch1_7_3d_visualization.py", line 45, in <module>
    gp.set_interpolator(geo_model)
  File "D:\python\gempy-main\gempy\api_modules\setters.py", line 108, in set_interpolator
    geo_model._interpolator.compile_th_fn_geo(inplace=True, grid=grid)
  File "D:\python\gempy-main\gempy\core\interpolator.py", line 1123, in compile_th_fn_geo
    self.theano_graph.theano_output(),
  File "D:\python\gempy-main\gempy\core\theano_modules\theano_graph_pro.py", line 631, in theano_output
    solutions[:9] = self.compute_series()
  File "D:\python\gempy-main\gempy\core\theano_modules\theano_graph_pro.py", line 465, in compute_series
    series, self.updates1 = theano.scan(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\scan_module\scan.py", line 774, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "D:\python\gempy-main\gempy\core\theano_modules\theano_graph_pro.py", line 2141, in compute_a_series
    self.compute_scalar_field(weights, grid,
  File "D:\python\gempy-main\gempy\core\theano_modules\theano_graph_pro.py", line 434, in compute_scalar_field
    return self.scalar_field_at_all(weights, grid_val, fault_matrix)
  File "D:\python\gempy-main\gempy\core\theano_modules\theano_graph_pro.py", line 1725, in scalar_field_at_all
    Z_x_loop, updates3 = theano.scan(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\scan_module\scan.py", line 843, in scan
    dummy_f = function(dummy_args,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\link.py", line 826, in make_all
    thunks += [node.op.make_thunk(node,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\scan_module\scan_op.py", line 861, in make_thunk
    self.fn = function(wrapped_inputs,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "D:\python\gempy-main\venv\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\vm.py", line 1087, in make_all
    thunks.append(node.op.make_thunk(node,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cmodule.py", line 2420, in compile_str
    return dlimport(lib_filename)
  File "D:\python\gempy-main\venv\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing m7b9aaee4c7e7a84c9349e61bca7c6a325d685aa6ac844a5dba2a836e7ea148e3
```
Run ch1_1_basics.py in tutorials folder and infomation showed like this. It seems lack of some so file?

**Comment by ounie-os** [comment]
Thank you for your reply @NilsChudalla 

Yes , gempy is installed in a fresh environment and these are installed packages below. My python interpreter is 3.8.10

appdirs==1.4.4
asttokens==2.2.1
backcall==0.2.0
certifi==2022.12.7
charset-normalizer==3.1.0
colorama==0.4.6
contourpy==1.0.7
cycler==0.11.0
decorator==5.1.1
exceptiongroup==1.1.1
executing==1.2.0
fonttools==4.39.3
GDAL @ file:///D:/python/gempy_project/venv/Scripts/GDAL-3.4.3-cp38-cp38-win_amd64.whl
gempy==2.2.12
idna==3.4
imageio==2.27.0
importlib-resources==5.12.0
iniconfig==2.0.0
ipython==8.12.0
jedi==0.18.2
kiwisolver==1.4.4
lazy_loader==0.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
networkx==3.1
numpy==1.21.6
packaging==23.0
pandas==1.3.4
parso==0.8.3
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.2.0
pluggy==1.0.0
pooch==1.7.0
prompt-toolkit==3.0.38
pure-eval==0.2.2
Pygments==2.14.0
pyparsing==3.0.9
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.1
pytest==7.3.0
python-dateutil==2.8.2
pytz==2023.3
pyvista==0.34.2
pyvistaqt==0.10.0
PyWavelets==1.4.1
QtPy==2.3.1
requests==2.28.2
scikit-image==0.20.0
scipy==1.9.1
scooby==0.7.1
seaborn==0.12.2
six==1.16.0
stack-data==0.6.2
Theano==1.0.5
tifffile==2023.3.21
tomli==2.0.1
traitlets==5.9.0
typing_extensions==4.5.0
urllib3==1.26.15
vtk==9.2.6
wcwidth==0.2.6
xarray==2022.3.0
zipp==3.15.0
