### ISSUE TITLE
AssertionError--How can I use this interpolation function without reporting an error?

### ISSUE THREAD

**Issue by qq123hht** [cgre-aachen/gempy#834]
gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])

The error is reported as follows：

Setting kriging parameters to their default values.
Compiling aesara function...
Traceback (most recent call last):
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1243, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1517, in make_thunk
    isinstance(out, TensorVariable) for out in self.fn.maker.fgraph.outputs
                                               ^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1449, in fn
    self._fn = pfunc(
               ^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\pfunc.py", line 367, in pfunc
    return orig_function(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1815, in orig_function
    fn = m.create(defaults)
         ^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1708, in create
    _fn, _i, _o = self.linker.make_thunk(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\basic.py", line 254, in make_thunk
    return self.make_all(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1297, in make_all
    vm = self.make_vm(
         ^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1020, in make_vm
    from aesara.link.c.cvm import CVM
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\c\cvm.py", line 13, in <module>
    from aesara.link.c.lazylinker_c import CLazyLinker
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\c\lazylinker_c.py", line 170, in <module>
    assert force_compile or (version == get_version())  # noqa
                             ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1243, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1517, in make_thunk
    isinstance(out, TensorVariable) for out in self.fn.maker.fgraph.outputs
                                               ^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1449, in fn
    self._fn = pfunc(
               ^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\pfunc.py", line 367, in pfunc
    return orig_function(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1815, in orig_function
    fn = m.create(defaults)
         ^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1708, in create
    _fn, _i, _o = self.linker.make_thunk(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\basic.py", line 254, in make_thunk
    return self.make_all(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1252, in make_all
    raise_with_op(fgraph, node)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\utils.py", line 533, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1243, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1517, in make_thunk
    isinstance(out, TensorVariable) for out in self.fn.maker.fgraph.outputs
                                               ^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\scan\op.py", line 1449, in fn
    self._fn = pfunc(
               ^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\pfunc.py", line 367, in pfunc
    return orig_function(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1815, in orig_function
    fn = m.create(defaults)
         ^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\types.py", line 1708, in create
    _fn, _i, _o = self.linker.make_thunk(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\basic.py", line 254, in make_thunk
    return self.make_all(
           ^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1297, in make_all
    vm = self.make_vm(
         ^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\vm.py", line 1020, in make_vm
    from aesara.link.c.cvm import CVM
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\c\cvm.py", line 13, in <module>
    from aesara.link.c.lazylinker_c import CLazyLinker
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\c\lazylinker_c.py", line 170, in <module>
    assert force_compile or (version == get_version())  # noqa
                             ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Apply node that caused the error: for{cpu,scan_fn}(Elemwise{scalar_minimum,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{Set;:int64:}.0)
Toposort index: 393
Inputs types: [TensorType(int64, ()), TensorType(float64, (?, ?)), TensorType(int32, (?,)), TensorType(int32, (?,)), TensorType(float64, (?, ?, 3))]
Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File "<ipython-input-2-25677ff23893>", line 1, in <module>
    runfile('D:\\PY3\\pythonProject\\123.py', wdir='D:\\PY3\\pythonProject')
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PY3\pythonProject\123.py", line 64, in <module>
    gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\api_modules\setters.py", line 80, in set_interpolator
    geo_model._interpolator.create_aesara_graph(geo_model._additional_data, inplace=True,
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\interpolator.py", line 118, in create_aesara_graph
    graph = tg.aesaraGraphPro(
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\aesara_modules\aesara_graph_pro.py", line 233, in __init__
    rest_ref_aux = self.set_rest_ref_matrix(self.number_of_points_per_surface_T)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\aesara_modules\aesara_graph_pro.py", line 795, in set_rest_ref_matrix
    ref_points_loop, update_ = aesara.scan(self.repeat_list,
Debug print of the apply node: 
for{cpu,scan_fn} [id A] <TensorType(float64, (?, ?, 3))>
 |Elemwise{scalar_minimum,no_inplace} [id B] <TensorType(int64, ())>

...

   |     |TensorConstant{3} [id DL] <TensorType(int8, ())>
   |ScalarConstant{1} [id DM] <int64>
Inner graphs:
for{cpu,scan_fn} [id A] <TensorType(float64, (?, ?, 3))>
 >IncSubtensor{Set;int32:int32:} [id DN] <TensorType(float64, (?, 3))>
 > |*3-<TensorType(float64, (?, 3))> [id DO] <TensorType(float64, (?, 3))> -> [id DB]
 
 > |ScalarFromTensor [id FB] <int32>
 > |ScalarFromTensor [id EL] <int32>
HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-25677ff23893>", line 1, in <module>
    runfile('D:\\PY3\\pythonProject\\123.py', wdir='D:\\PY3\\pythonProject')
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PY3\pythonProject\123.py", line 64, in <module>
    gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\api_modules\setters.py", line 109, in set_interpolator
    geo_model._interpolator.compile_th_fn_geo(inplace=True, grid=grid)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\interpolator.py", line 1123, in compile_th_fn_geo
    th_fn = aesara.function(inputs=input_data_T,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\compile\function\__init__.py", line 317, in function
    fn = pfunc(
         ^^^^^^
...

  File "D:\software\anaconda\envs\gempy\Lib\site-packages\aesara\link\c\lazylinker_c.py", line 170, in <module>
    assert force_compile or (version == get_version())  # noqa
                             ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 
Apply node that caused the error: for{cpu,scan_fn}(Elemwise{scalar_minimum,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{Set;:int64:}.0)
Toposort index: 393
Inputs types: [TensorType(int64, ()), TensorType(float64, (?, ?)), TensorType(int32, (?,)), TensorType(int32, (?,)), TensorType(float64, (?, ?, 3))]
Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File "<ipython-input-2-25677ff23893>", line 1, in <module>
    runfile('D:\\PY3\\pythonProject\\123.py', wdir='D:\\PY3\\pythonProject')
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\software\Pycharm\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PY3\pythonProject\123.py", line 64, in <module>
    gp.set_interpolator(geo_model, theano_optimizer='fast_compile', verbose=[])
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\api_modules\setters.py", line 80, in set_interpolator
    geo_model._interpolator.create_aesara_graph(geo_model._additional_data, inplace=True,
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\interpolator.py", line 118, in create_aesara_graph
    graph = tg.aesaraGraphPro(
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\aesara_modules\aesara_graph_pro.py", line 233, in __init__
    rest_ref_aux = self.set_rest_ref_matrix(self.number_of_points_per_surface_T)
  File "D:\software\anaconda\envs\gempy\Lib\site-packages\gempy\core\aesara_modules\aesara_graph_pro.py", line 795, in set_rest_ref_matrix
    ref_points_loop, update_ = aesara.scan(self.repeat_list,
Debug print of the apply node: 
for{cpu,scan_fn} [id A] <TensorType(float64, (?, ?, 3))>
 |Elemwise{scalar_minimum,no_inplace} [id B] <TensorType(int64, ())>
 | |Elemwise{scalar_minimum,no_inplace} [id C] <TensorType(int64, ())>

...

 > |ScalarFromTensor [id FB] <int32>
 > |ScalarFromTensor [id EL] <int32>
HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.
Apply node that caused the error: for{cpu,Looping}(Elemwise{scalar_minimum,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, IncSubtensor{Set;:int64:}.0, Number of points per surface used to split rest-ref, fault relation matrix, <TensorType(float64, ())>, <TensorType(float64, ())>, <TensorType(float64, ())>, Nugget effect of gradients, Nugget effect of scalar, Attenuation factor, Sigmoid Outside, Sigmoid slope, <TensorType(int32, (?,))>, <TensorType(bool, (?,))>, <TensorType(int32, (?,))>, Coordinates of the grid points to interpolate, All the surface_points points at once, Position of the dips, Angle of every dip, Azimuth, Polarity, Values that the blocks are taking)
Toposort index: 390

...

for{cpu,Looping}.6 [id A] <TensorType(float64, (?, ?, ?, ?))>
 >IncSubtensor{Set;int32, ::, int8:int64:} [id QL] <TensorType(float64, (?, ?, ?))>
 >IncSubtensor{Set;int32:int32:} [id RI] <TensorType(float64, (?,))>
 >IncSubtensor{Set;int32, int8:int64:} [id RS] <TensorType(float64, (?, ?))>
 >AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True} [id RY] <TensorType(float64, (?, ?))>
 >IncSubtensor{Set;int32, int8:int64:} [id SS] <TensorType(bool, (?, ?))>
 >AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True} [id WN] <TensorType(bool, (?, ?))>
 >IncSubtensor{Set;int32, ::, int8:int64:} [id XQ] <TensorType(float64, (?, ?, ?))>
 >Elemwise{mul,no_inplace} [id UO] <TensorType(int64, ())>
for{cpu,Looping}.7 [id A] <TensorType(int64, (?,))>
 >IncSubtensor{Set;int32, ::, int8:int64:} [id QL] <TensorType(float64, (?, ?, ?))>
 >IncSubtensor{Set;int32:int32:} [id RI] <TensorType(float64, (?,))>
 >IncSubtensor{Set;int32, int8:int64:} [id RS] <TensorType(float64, (?, ?))>
 >AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True} [id RY] <TensorType(float64, (?, ?))>
 >IncSubtensor{Set;int32, int8:int64:} [id SS] <TensorType(bool, (?, ?))>
 >AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=True} [id WN] <TensorType(bool, (?, ?))>
 >IncSubtensor{Set;int32, ::, int8:int64:} [id XQ] <TensorType(float64, (?, ?, ?))>
 >Elemwise{mul,no_inplace} [id UO] <TensorType(int64, ())>
HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.

**Comment by AlexanderJuestel** [comment]
Hello,
Please describe your error in more detail and not just by posting the error message.

Thanks

**Comment by qq123hht** [comment]
Sorry.
I just started using gmpy recently, and I want to try to see if gmpy is installed successfully, but it reports this error message every time I call the function gp.set_interpolator(), while all the other functions of gmpy are normal.
My gempy is version 2.3.1, theano is 1.0.5, and aesara is 2.9.1.
Thanks.
