### ISSUE TITLE
utf-8 Error

### ISSUE THREAD

**Issue by gasiva** [cgre-aachen/gempy#92]
I'm trying to run this code related to one ot the gempy tutorials:

#### -*- coding: utf-8 -*-
import gempy as gp
import os
import numpy as np

geo_data = gp.create_data(extent=[0,20,0,10,-10,0],
              resolution=[80,40,40],
              path_o = os.getcwd() + "\gempy-paper\paper_Orientations.csv",
              path_i = os.getcwd() + "\gempy-paper\paper_Points.csv")

gp.set_series(geo_data, series_distribution={'younger_serie' : 'Unconformity',
                                             'fault_serie1': 'fault',
                                             'older_serie': ('Layer2', 'Layer1')})

interp_data = gp.InterpolatorData(geo_data, compile_theano=True, theano_optimizer= 'fast_compile')
lith, fault = gp.compute_model(interp_data)
ver, sim = gp.get_surfaces(interp_data,lith[1], [fault[1]], original_scale=True)
np.save('surfaces_tut_paper', (ver, sim))
gp.plot_surfaces_3D(geo_data, ver, sim)

And I get the following Error:

'C:\Users\UENTE\Anaconda3\lib\site-packages\gempy\plotting\visualization.py:36: UserWarning: Steno 3D package is not installed. No 3D online visualization available.
  warnings.warn('Steno 3D package is not installed. No 3D online visualization available.')
Traceback (most recent call last):

  File "<ipython-input-1-5dc6b9b11964>", line 1, in <module>
    runfile('//fs/lavori/#Python-Apps/gemPy/tutorial-paper.py', wdir='//fs/lavori/#Python-Apps/gemPy')

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "//fs/lavori/#Python-Apps/gemPy/tutorial-paper.py", line 7, in <module>
    import gempy as gp

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\gempy\__init__.py", line 16, in <module>
    from .gempy_front import *

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\gempy\gempy_front.py", line 43, in <module>
    from gempy.interpolator import InterpolatorData

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\gempy\interpolator.py", line 28, in <module>
    from gempy import theano_graph

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\gempy\theano_graph.py", line 26, in <module>
    import theano

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\__init__.py", line 124, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\scan_module\__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\scan_module\scan_opt.py", line 60, in <module>
    from theano import tensor, scalar

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\tensor\__init__.py", line 17, in <module>
    from theano.tensor import blas

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\tensor\blas.py", line 155, in <module>
    from theano.tensor.blas_headers import blas_header_text

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\tensor\blas_headers.py", line 987, in <module>
    if not config.blas.ldflags:

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\configparser.py", line 332, in __get__
    val_str = self.default()

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\configdefaults.py", line 1412, in default_blas_ldflags
    res = try_blas_flag(flags)

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\configdefaults.py", line 1519, in try_blas_flag
    flags=cflags, try_run=True)

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2224, in try_compile_tmp
    comp_args)

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1796, in _try_compile_tmp
    args = cls.compile_args()

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1995, in compile_args
    native_lines = get_lines("%s -march=native -E -v -" % theano.config.cxx)

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 1979, in get_lines
    for line in lines:

  File "C:\Users\UENTE\Anaconda3\lib\site-packages\theano\compat\__init__.py", line 47, in decode_iter
    yield x.decode()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 8: invalid start byte'

Someone can help?

**Comment by Leguark** [comment]
Hi there! That really looks like a problem of setting the paths for theano-compiler properly. In windows a compiler does not come built in so depending what you install first in many cases the paths get wrong.
1) First just check that is a theano problem by trying to run a simple theano example
2) Go to the theano documentation and try to figure it out
3) Something that tends to work is: first installing the compiler, uninstall conda, install conda with the tick on adding paths to the global enviroment.
4) If nothing works install Linux :p

Good luck

**Comment by gasiva** [comment]
Problem solved.
At the beginnig of Anaconda installation I had to check 'For all users' 
and not 'Just for me'
Thank you
